/*\n  # Add invitation token columns for invited users\n\n  1. Changes to CRM tables\n    - Add `invitation_token` column to store unique invitation tokens\n    - Add `invitation_token_expires_at` column to track token expiration\n    - These columns enable secure invitation flows where users authenticate with their CRM before verifying WhatsApp\n\n  2. Notes\n    - Tokens are generated when inviting team members\n    - Tokens expire after 24 hours for security\n    - Once used, tokens are cleared from the database\n*/\n\n-- Add invitation token columns to teamleader_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'invitation_token'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN invitation_token text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'invitation_token_expires_at'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN invitation_token_expires_at timestamptz;
\n  END IF;
\nEND $$;
\n\n-- Add invitation token columns to pipedrive_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'invitation_token'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN invitation_token text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'invitation_token_expires_at'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN invitation_token_expires_at timestamptz;
\n  END IF;
\nEND $$;
\n\n-- Add invitation token columns to odoo_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'odoo_users' AND column_name = 'invitation_token'\n  ) THEN\n    ALTER TABLE odoo_users ADD COLUMN invitation_token text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'odoo_users' AND column_name = 'invitation_token_expires_at'\n  ) THEN\n    ALTER TABLE odoo_users ADD COLUMN invitation_token_expires_at timestamptz;
\n  END IF;
\nEND $$;
;
