/*\n  # Add trial started tracking to CRM tables\n\n  1. Changes\n    - Add `trial_started_tracked` boolean column to teamleader_users, pipedrive_users, and odoo_users\n    - Defaults to false for new users\n    - Set to true after first Trial_started analytics event is fired\n    \n  2. Purpose\n    - Prevents duplicate Trial_started events from inflating conversion metrics\n    - Ensures event only fires once per user account, regardless of page refreshes or callback re-runs\n    \n  3. Security\n    - Users can read their own trial_started_tracked status\n    - Only the user themselves can update it\n*/\n\n-- Add trial_started_tracked column to teamleader_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'trial_started_tracked'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN trial_started_tracked boolean DEFAULT false;
\n  END IF;
\nEND $$;
\n\n-- Add trial_started_tracked column to pipedrive_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'trial_started_tracked'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN trial_started_tracked boolean DEFAULT false;
\n  END IF;
\nEND $$;
\n\n-- Add trial_started_tracked column to odoo_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'odoo_users' AND column_name = 'trial_started_tracked'\n  ) THEN\n    ALTER TABLE odoo_users ADD COLUMN trial_started_tracked boolean DEFAULT false;
\n  END IF;
\nEND $$;
\n\n-- Create indexes for efficient lookups\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_trial_tracked ON teamleader_users(trial_started_tracked);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_trial_tracked ON pipedrive_users(trial_started_tracked);
\nCREATE INDEX IF NOT EXISTS idx_odoo_users_trial_tracked ON odoo_users(trial_started_tracked);
\n;
