/*\n  # Add auth_user_id to CRM tables\n\n  1. Changes to CRM tables\n    - Add `auth_user_id` column to teamleader_users, pipedrive_users, and odoo_users\n    - This column links CRM users to auth users who verified their WhatsApp\n    - Nullable to support existing users who haven't completed WhatsApp verification yet\n\n  2. Notes\n    - Column is populated when users complete WhatsApp verification with authentication\n    - Allows tracking which auth user owns each CRM user record\n*/\n\n-- Add auth_user_id column to teamleader_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'auth_user_id'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN auth_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Add auth_user_id column to pipedrive_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'auth_user_id'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN auth_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Add auth_user_id column to odoo_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'odoo_users' AND column_name = 'auth_user_id'\n  ) THEN\n    ALTER TABLE odoo_users ADD COLUMN auth_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE;
\n  END IF;
\nEND $$;
\n\n-- Create indexes for efficient queries\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_auth_user_id ON teamleader_users(auth_user_id);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_auth_user_id ON pipedrive_users(auth_user_id);
\nCREATE INDEX IF NOT EXISTS idx_odoo_users_auth_user_id ON odoo_users(auth_user_id);
\n;
