\n\n-- Add team member fields to teamleader_users table\nALTER TABLE teamleader_users \nADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false,\nADD COLUMN IF NOT EXISTS admin_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,\nADD COLUMN IF NOT EXISTS invited_by uuid REFERENCES auth.users(id),\nADD COLUMN IF NOT EXISTS invitation_status text DEFAULT 'pending' CHECK (invitation_status IN ('pending', 'accepted', 'declined')),\nADD COLUMN IF NOT EXISTS invited_at timestamptz DEFAULT now();
\n\n-- Add team member fields to pipedrive_users table\nALTER TABLE pipedrive_users \nADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false,\nADD COLUMN IF NOT EXISTS admin_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,\nADD COLUMN IF NOT EXISTS invited_by uuid REFERENCES auth.users(id),\nADD COLUMN IF NOT EXISTS invitation_status text DEFAULT 'pending' CHECK (invitation_status IN ('pending', 'accepted', 'declined')),\nADD COLUMN IF NOT EXISTS invited_at timestamptz DEFAULT now();
\n\n-- Add team member fields to odoo_users table\nALTER TABLE odoo_users \nADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false,\nADD COLUMN IF NOT EXISTS admin_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,\nADD COLUMN IF NOT EXISTS invited_by uuid REFERENCES auth.users(id),\nADD COLUMN IF NOT EXISTS invitation_status text DEFAULT 'pending' CHECK (invitation_status IN ('pending', 'accepted', 'declined')),\nADD COLUMN IF NOT EXISTS invited_at timestamptz DEFAULT now();
\n\n-- Update existing users to be admins (users who created their own accounts)\nUPDATE teamleader_users SET is_admin = true WHERE admin_user_id IS NULL;
\nUPDATE pipedrive_users SET is_admin = true WHERE admin_user_id IS NULL;
\nUPDATE odoo_users SET is_admin = true WHERE admin_user_id IS NULL;
\n\n-- Create indexes for efficient team member queries\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_admin_user_id ON teamleader_users(admin_user_id);
\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_is_admin ON teamleader_users(is_admin);
\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_invitation_status ON teamleader_users(invitation_status);
\n\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_admin_user_id ON pipedrive_users(admin_user_id);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_is_admin ON pipedrive_users(is_admin);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_invitation_status ON pipedrive_users(invitation_status);
\n\nCREATE INDEX IF NOT EXISTS idx_odoo_users_admin_user_id ON odoo_users(admin_user_id);
\nCREATE INDEX IF NOT EXISTS idx_odoo_users_is_admin ON odoo_users(is_admin);
\nCREATE INDEX IF NOT EXISTS idx_odoo_users_invitation_status ON odoo_users(invitation_status);
\n\n-- Update RLS policies for teamleader_users\nDROP POLICY IF EXISTS "Users can view their own TeamLeader data" ON teamleader_users;
\nDROP POLICY IF EXISTS "Users can insert their own TeamLeader data" ON teamleader_users;
\nDROP POLICY IF EXISTS "Users can update their own TeamLeader data" ON teamleader_users;
\n\nCREATE POLICY "Users can view their own and team data" ON teamleader_users\n  FOR SELECT TO authenticated\n  USING (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid() OR\n    user_id IN (\n      SELECT user_id FROM teamleader_users \n      WHERE admin_user_id = auth.uid() AND deleted_at IS NULL\n    )\n  );
\n\nCREATE POLICY "Admins can insert team members" ON teamleader_users\n  FOR INSERT TO authenticated\n  WITH CHECK (\n    user_id = auth.uid() OR \n    (admin_user_id = auth.uid() AND invited_by = auth.uid())\n  );
\n\nCREATE POLICY "Users can update their own data, admins can update team data" ON teamleader_users\n  FOR UPDATE TO authenticated\n  USING (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid()\n  )\n  WITH CHECK (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid()\n  );
\n\n-- Update RLS policies for pipedrive_users\nDROP POLICY IF EXISTS "Users can view their own Pipedrive data" ON pipedrive_users;
\nDROP POLICY IF EXISTS "Users can insert their own Pipedrive data" ON pipedrive_users;
\nDROP POLICY IF EXISTS "Users can update their own Pipedrive data" ON pipedrive_users;
\n\nCREATE POLICY "Users can view their own and team data" ON pipedrive_users\n  FOR SELECT TO authenticated\n  USING (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid() OR\n    user_id IN (\n      SELECT user_id FROM pipedrive_users \n      WHERE admin_user_id = auth.uid() AND deleted_at IS NULL\n    )\n  );
\n\nCREATE POLICY "Admins can insert team members" ON pipedrive_users\n  FOR INSERT TO authenticated\n  WITH CHECK (\n    user_id = auth.uid() OR \n    (admin_user_id = auth.uid() AND invited_by = auth.uid())\n  );
\n\nCREATE POLICY "Users can update their own data, admins can update team data" ON pipedrive_users\n  FOR UPDATE TO authenticated\n  USING (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid()\n  )\n  WITH CHECK (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid()\n  );
\n\n-- Update RLS policies for odoo_users\nDROP POLICY IF EXISTS "Users can view their own Odoo data" ON odoo_users;
\nDROP POLICY IF EXISTS "Users can insert their own Odoo data" ON odoo_users;
\nDROP POLICY IF EXISTS "Users can update their own Odoo data" ON odoo_users;
\n\nCREATE POLICY "Users can view their own and team data" ON odoo_users\n  FOR SELECT TO authenticated\n  USING (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid() OR\n    user_id IN (\n      SELECT user_id FROM odoo_users \n      WHERE admin_user_id = auth.uid() AND deleted_at IS NULL\n    )\n  );
\n\nCREATE POLICY "Admins can insert team members" ON odoo_users\n  FOR INSERT TO authenticated\n  WITH CHECK (\n    user_id = auth.uid() OR \n    (admin_user_id = auth.uid() AND invited_by = auth.uid())\n  );
\n\nCREATE POLICY "Users can update their own data, admins can update team data" ON odoo_users\n  FOR UPDATE TO authenticated\n  USING (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid()\n  )\n  WITH CHECK (\n    user_id = auth.uid() OR \n    admin_user_id = auth.uid()\n  );
;
