\n\n-- Add WhatsApp fields to teamleader_users table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'whatsapp_number'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN whatsapp_number text;
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'whatsapp_status'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN whatsapp_status text DEFAULT 'not_set';
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'whatsapp_otp_code'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN whatsapp_otp_code text;
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'whatsapp_otp_expires_at'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN whatsapp_otp_expires_at timestamptz;
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'whatsapp_otp_phone'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN whatsapp_otp_phone text;
\n  END IF;
\nEND $$;
\n\n-- Add WhatsApp fields to pipedrive_users table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'whatsapp_number'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN whatsapp_number text;
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'whatsapp_status'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN whatsapp_status text DEFAULT 'not_set';
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'whatsapp_otp_code'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN whatsapp_otp_code text;
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'whatsapp_otp_expires_at'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN whatsapp_otp_expires_at timestamptz;
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'whatsapp_otp_phone'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN whatsapp_otp_phone text;
\n  END IF;
\nEND $$;
\n\n-- Add check constraints for WhatsApp status\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.constraint_column_usage\n    WHERE table_name = 'teamleader_users' AND constraint_name = 'teamleader_users_whatsapp_status_check'\n  ) THEN\n    ALTER TABLE teamleader_users ADD CONSTRAINT teamleader_users_whatsapp_status_check \n    CHECK (whatsapp_status IN ('not_set', 'pending', 'active'));
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.constraint_column_usage\n    WHERE table_name = 'pipedrive_users' AND constraint_name = 'pipedrive_users_whatsapp_status_check'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD CONSTRAINT pipedrive_users_whatsapp_status_check \n    CHECK (whatsapp_status IN ('not_set', 'pending', 'active'));
\n  END IF;
\nEND $$;
\n\n-- Add indexes for performance\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_whatsapp_number ON teamleader_users (whatsapp_number);
\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_whatsapp_status ON teamleader_users (whatsapp_status);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_whatsapp_number ON pipedrive_users (whatsapp_number);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_whatsapp_status ON pipedrive_users (whatsapp_status);
;
