/*\n  # Add Language Preference Columns\n\n  1. Changes\n    - Add `language_preference` column to `odoo_users` table\n    - Add `language_preference` column to `pipedrive_users` table\n    - Column will store language codes: 'en', 'nl', 'fr', 'de'\n\n  2. Notes\n    - The column is added with lowercase naming convention for consistency\n    - Default value is NULL to allow users to set their preference\n*/\n\n-- Add language_preference column to odoo_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'odoo_users' AND column_name = 'language_preference'\n  ) THEN\n    ALTER TABLE odoo_users ADD COLUMN language_preference text;
\n  END IF;
\nEND $$;
\n\n-- Add language_preference column to pipedrive_users\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'language_preference'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN language_preference text;
\n  END IF;
\nEND $$;
\n\n-- Rename Language_Preference to language_preference in teamleader_users for consistency\nDO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'Language_Preference'\n  ) THEN\n    ALTER TABLE teamleader_users RENAME COLUMN "Language_Preference" TO language_preference;
\n  END IF;
\nEND $$;
;
