\n\n-- Drop existing problematic policies\nDROP POLICY IF EXISTS "Users can view their own and team data" ON teamleader_users;
\nDROP POLICY IF EXISTS "Users can update their own data, admins can update team data" ON teamleader_users;
\nDROP POLICY IF EXISTS "Admins can insert team members" ON teamleader_users;
\nDROP POLICY IF EXISTS "allow user insert own teamleader record" ON teamleader_users;
\nDROP POLICY IF EXISTS "allow user update own teamleader record" ON teamleader_users;
\n\nDROP POLICY IF EXISTS "Users can view their own and team data" ON pipedrive_users;
\nDROP POLICY IF EXISTS "Users can update their own data, admins can update team data" ON pipedrive_users;
\nDROP POLICY IF EXISTS "Admins can insert team members" ON pipedrive_users;
\nDROP POLICY IF EXISTS "allow user insert own pipedrive record" ON pipedrive_users;
\nDROP POLICY IF EXISTS "allow user update own pipedrive record" ON pipedrive_users;
\nDROP POLICY IF EXISTS "allow_postgres_inserts" ON pipedrive_users;
\n\nDROP POLICY IF EXISTS "Users can view their own and team data" ON odoo_users;
\nDROP POLICY IF EXISTS "Users can update their own data, admins can update team data" ON odoo_users;
\nDROP POLICY IF EXISTS "Admins can insert team members" ON odoo_users;
\n\n-- Create simplified, non-recursive policies for teamleader_users\nCREATE POLICY "teamleader_users_select_own_data"\n  ON teamleader_users\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid() AND deleted_at IS NULL);
\n\nCREATE POLICY "teamleader_users_select_admin_team"\n  ON teamleader_users\n  FOR SELECT\n  TO authenticated\n  USING (admin_user_id = auth.uid() AND deleted_at IS NULL);
\n\nCREATE POLICY "teamleader_users_insert_own"\n  ON teamleader_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "teamleader_users_insert_team_member"\n  ON teamleader_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (admin_user_id = auth.uid() AND invited_by = auth.uid());
\n\nCREATE POLICY "teamleader_users_update_own"\n  ON teamleader_users\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "teamleader_users_update_team_member"\n  ON teamleader_users\n  FOR UPDATE\n  TO authenticated\n  USING (admin_user_id = auth.uid())\n  WITH CHECK (admin_user_id = auth.uid());
\n\n-- Create simplified, non-recursive policies for pipedrive_users\nCREATE POLICY "pipedrive_users_select_own_data"\n  ON pipedrive_users\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid() AND deleted_at IS NULL);
\n\nCREATE POLICY "pipedrive_users_select_admin_team"\n  ON pipedrive_users\n  FOR SELECT\n  TO authenticated\n  USING (admin_user_id = auth.uid() AND deleted_at IS NULL);
\n\nCREATE POLICY "pipedrive_users_insert_own"\n  ON pipedrive_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "pipedrive_users_insert_team_member"\n  ON pipedrive_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (admin_user_id = auth.uid() AND invited_by = auth.uid());
\n\nCREATE POLICY "pipedrive_users_update_own"\n  ON pipedrive_users\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "pipedrive_users_update_team_member"\n  ON pipedrive_users\n  FOR UPDATE\n  TO authenticated\n  USING (admin_user_id = auth.uid())\n  WITH CHECK (admin_user_id = auth.uid());
\n\n-- Create simplified, non-recursive policies for odoo_users\nCREATE POLICY "odoo_users_select_own_data"\n  ON odoo_users\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid() AND deleted_at IS NULL);
\n\nCREATE POLICY "odoo_users_select_admin_team"\n  ON odoo_users\n  FOR SELECT\n  TO authenticated\n  USING (admin_user_id = auth.uid() AND deleted_at IS NULL);
\n\nCREATE POLICY "odoo_users_insert_own"\n  ON odoo_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "odoo_users_insert_team_member"\n  ON odoo_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (admin_user_id = auth.uid() AND invited_by = auth.uid());
\n\nCREATE POLICY "odoo_users_update_own"\n  ON odoo_users\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "odoo_users_update_team_member"\n  ON odoo_users\n  FOR UPDATE\n  TO authenticated\n  USING (admin_user_id = auth.uid())\n  WITH CHECK (admin_user_id = auth.uid());
;
