\n\n-- Add stripe_customer_id to teamleader_users table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'teamleader_users' AND column_name = 'stripe_customer_id'\n  ) THEN\n    ALTER TABLE teamleader_users ADD COLUMN stripe_customer_id text;
\n  END IF;
\nEND $$;
\n\n-- Add stripe_customer_id to pipedrive_users table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'pipedrive_users' AND column_name = 'stripe_customer_id'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD COLUMN stripe_customer_id text;
\n  END IF;
\nEND $$;
\n\n-- Add unique constraints for stripe_customer_id (if they don't exist)\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE table_name = 'teamleader_users' AND constraint_name = 'teamleader_users_stripe_customer_id_key'\n  ) THEN\n    ALTER TABLE teamleader_users ADD CONSTRAINT teamleader_users_stripe_customer_id_key UNIQUE (stripe_customer_id);
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE table_name = 'pipedrive_users' AND constraint_name = 'pipedrive_users_stripe_customer_id_key'\n  ) THEN\n    ALTER TABLE pipedrive_users ADD CONSTRAINT pipedrive_users_stripe_customer_id_key UNIQUE (stripe_customer_id);
\n  END IF;
\nEND $$;
\n\n-- Add indexes for performance (if they don't exist)\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_indexes\n    WHERE tablename = 'teamleader_users' AND indexname = 'idx_teamleader_users_stripe_customer_id'\n  ) THEN\n    CREATE INDEX idx_teamleader_users_stripe_customer_id ON teamleader_users (stripe_customer_id);
\n  END IF;
\nEND $$;
\n\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_indexes\n    WHERE tablename = 'pipedrive_users' AND indexname = 'idx_pipedrive_users_stripe_customer_id'\n  ) THEN\n    CREATE INDEX idx_pipedrive_users_stripe_customer_id ON pipedrive_users (stripe_customer_id);
\n  END IF;
\nEND $$;
;
