\n\n-- Drop existing policies to recreate them\nDROP POLICY IF EXISTS "Users can insert own data" ON users;
\nDROP POLICY IF EXISTS "Users can read own data" ON users;
\nDROP POLICY IF EXISTS "Users can update own data" ON users;
\n\n-- Add new columns if they don't exist\nDO $$\nBEGIN\n  -- Add teamleader_id column\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'teamleader_id'\n  ) THEN\n    ALTER TABLE users ADD COLUMN teamleader_id text UNIQUE;
\n  END IF;
\n\n  -- Add display_name column for better user identification\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'display_name'\n  ) THEN\n    ALTER TABLE users ADD COLUMN display_name text;
\n  END IF;
\n\n  -- Add avatar_url column\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'avatar_url'\n  ) THEN\n    ALTER TABLE users ADD COLUMN avatar_url text;
\n  END IF;
\n\n  -- Add language and timezone from TeamLeader\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'language'\n  ) THEN\n    ALTER TABLE users ADD COLUMN language text DEFAULT 'en';
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'timezone'\n  ) THEN\n    ALTER TABLE users ADD COLUMN timezone text DEFAULT 'UTC';
\n  END IF;
\n\n  -- Add last_login tracking\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'last_login'\n  ) THEN\n    ALTER TABLE users ADD COLUMN last_login timestamptz;
\n  END IF;
\n\n  -- Add status column for user management\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'status'\n  ) THEN\n    ALTER TABLE users ADD COLUMN status text DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended'));
\n  END IF;
\nEND $$;
\n\n-- Update existing columns to have better constraints\nALTER TABLE users \n  ALTER COLUMN name SET NOT NULL,\n  ALTER COLUMN email SET NOT NULL;
\n\n-- Add unique constraint on teamleader_id if it doesn't exist\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.table_constraints\n    WHERE table_name = 'users' AND constraint_name = 'users_teamleader_id_key'\n  ) THEN\n    ALTER TABLE users ADD CONSTRAINT users_teamleader_id_key UNIQUE (teamleader_id);
\n  END IF;
\nEND $$;
\n\n-- Create indexes for better performance\nCREATE INDEX IF NOT EXISTS idx_users_teamleader_id ON users(teamleader_id);
\nCREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
\nCREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
\nCREATE INDEX IF NOT EXISTS idx_users_last_login ON users(last_login);
\nCREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);
\n\n-- Update RLS policies with better security\nCREATE POLICY "Users can insert own data"\n  ON users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "Users can read own data"\n  ON users\n  FOR SELECT\n  TO authenticated\n  USING (auth.uid() = id);
\n\nCREATE POLICY "Users can update own data"\n  ON users\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Create a function to update last_login automatically\nCREATE OR REPLACE FUNCTION update_user_last_login()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.last_login = now();
\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Create trigger for last_login updates (only if it doesn't exist)\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.triggers\n    WHERE trigger_name = 'update_user_last_login_trigger'\n  ) THEN\n    CREATE TRIGGER update_user_last_login_trigger\n      BEFORE UPDATE OF teamleader_access_token ON users\n      FOR EACH ROW\n      EXECUTE FUNCTION update_user_last_login();
\n  END IF;
\nEND $$;
\n\n-- Create a function to get user by TeamLeader ID\nCREATE OR REPLACE FUNCTION get_user_by_teamleader_id(tl_id text)\nRETURNS TABLE (\n  id uuid,\n  name text,\n  email text,\n  display_name text,\n  teamleader_id text,\n  language text,\n  timezone text,\n  status text,\n  created_at timestamptz,\n  updated_at timestamptz,\n  last_login timestamptz\n) \nSECURITY DEFINER\nAS $$\nBEGIN\n  RETURN QUERY\n  SELECT \n    u.id,\n    u.name,\n    u.email,\n    u.display_name,\n    u.teamleader_id,\n    u.language,\n    u.timezone,\n    u.status,\n    u.created_at,\n    u.updated_at,\n    u.last_login\n  FROM users u\n  WHERE u.teamleader_id = tl_id\n  AND u.status = 'active';
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Add comments for documentation\nCOMMENT ON TABLE users IS 'User accounts integrated with TeamLeader CRM';
\nCOMMENT ON COLUMN users.teamleader_id IS 'Unique TeamLeader user identifier';
\nCOMMENT ON COLUMN users.display_name IS 'User display name from TeamLeader';
\nCOMMENT ON COLUMN users.language IS 'User preferred language from TeamLeader';
\nCOMMENT ON COLUMN users.timezone IS 'User timezone from TeamLeader';
\nCOMMENT ON COLUMN users.teamleader_user_info IS 'Complete TeamLeader user profile data';
\nCOMMENT ON COLUMN users.teamleader_access_token IS 'TeamLeader API access token';
\nCOMMENT ON COLUMN users.teamleader_refresh_token IS 'TeamLeader API refresh token';
\nCOMMENT ON COLUMN users.teamleader_token_expires_at IS 'TeamLeader token expiration timestamp';
\nCOMMENT ON COLUMN users.status IS 'User account status (active, inactive, suspended)';
\nCOMMENT ON COLUMN users.last_login IS 'Timestamp of last successful login';
;
