\n\n-- Create teamleader_users table\nCREATE TABLE IF NOT EXISTS teamleader_users (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n  teamleader_id text UNIQUE NOT NULL,\n  access_token text,\n  refresh_token text,\n  token_expires_at timestamptz,\n  user_info jsonb,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now(),\n  deleted_at timestamptz\n);
\n\n-- Create pipedrive_users table\nCREATE TABLE IF NOT EXISTS pipedrive_users (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n  pipedrive_user_id text UNIQUE NOT NULL,\n  access_token text,\n  refresh_token text,\n  token_expires_at timestamptz,\n  user_info jsonb,\n  api_domain text,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now(),\n  deleted_at timestamptz\n);
\n\n-- Enable RLS on new tables\nALTER TABLE teamleader_users ENABLE ROW LEVEL SECURITY;
\nALTER TABLE pipedrive_users ENABLE ROW LEVEL SECURITY;
\n\n-- Add RLS policies for teamleader_users\nCREATE POLICY "Users can view their own TeamLeader data"\n  ON teamleader_users\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can insert their own TeamLeader data"\n  ON teamleader_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "Users can update their own TeamLeader data"\n  ON teamleader_users\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\n-- Add RLS policies for pipedrive_users\nCREATE POLICY "Users can view their own Pipedrive data"\n  ON pipedrive_users\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can insert their own Pipedrive data"\n  ON pipedrive_users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "Users can update their own Pipedrive data"\n  ON pipedrive_users\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\n-- Migrate existing TeamLeader data if columns exist\nDO $$\nBEGIN\n  -- Check if teamleader_id column exists and migrate data\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'teamleader_id'\n  ) THEN\n    -- Migrate existing TeamLeader data\n    INSERT INTO teamleader_users (\n      user_id,\n      teamleader_id,\n      access_token,\n      refresh_token,\n      token_expires_at,\n      user_info,\n      created_at,\n      updated_at\n    )\n    SELECT \n      id,\n      teamleader_id,\n      teamleader_access_token,\n      teamleader_refresh_token,\n      teamleader_token_expires_at,\n      teamleader_user_info,\n      created_at,\n      updated_at\n    FROM users \n    WHERE teamleader_id IS NOT NULL\n    ON CONFLICT (teamleader_id) DO NOTHING;
\n  END IF;
\nEND $$;
\n\n-- Add indexes for performance\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_user_id ON teamleader_users(user_id);
\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_teamleader_id ON teamleader_users(teamleader_id);
\nCREATE INDEX IF NOT EXISTS idx_teamleader_users_deleted_at ON teamleader_users(deleted_at);
\n\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_user_id ON pipedrive_users(user_id);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_pipedrive_user_id ON pipedrive_users(pipedrive_user_id);
\nCREATE INDEX IF NOT EXISTS idx_pipedrive_users_deleted_at ON pipedrive_users(deleted_at);
\n\n-- Add updated_at trigger for new tables\nCREATE TRIGGER teamleader_users_updated_at\n  BEFORE UPDATE ON teamleader_users\n  FOR EACH ROW\n  EXECUTE FUNCTION handle_updated_at();
\n\nCREATE TRIGGER pipedrive_users_updated_at\n  BEFORE UPDATE ON pipedrive_users\n  FOR EACH ROW\n  EXECUTE FUNCTION handle_updated_at();
\n\n-- Remove TeamLeader-specific columns from users table (after migration)\nDO $$\nBEGIN\n  -- Remove TeamLeader columns if they exist\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'teamleader_access_token'\n  ) THEN\n    ALTER TABLE users DROP COLUMN teamleader_access_token;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'teamleader_refresh_token'\n  ) THEN\n    ALTER TABLE users DROP COLUMN teamleader_refresh_token;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'teamleader_token_expires_at'\n  ) THEN\n    ALTER TABLE users DROP COLUMN teamleader_token_expires_at;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'teamleader_user_info'\n  ) THEN\n    ALTER TABLE users DROP COLUMN teamleader_user_info;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'teamleader_id'\n  ) THEN\n    ALTER TABLE users DROP COLUMN teamleader_id;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'display_name'\n  ) THEN\n    ALTER TABLE users DROP COLUMN display_name;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'avatar_url'\n  ) THEN\n    ALTER TABLE users DROP COLUMN avatar_url;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'language'\n  ) THEN\n    ALTER TABLE users DROP COLUMN language;
\n  END IF;
\n\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'users' AND column_name = 'timezone'\n  ) THEN\n    ALTER TABLE users DROP COLUMN timezone;
\n  END IF;
\nEND $$;
;
